apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: test-bot-01
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/test-bot-01:2fc751e788e90c6840bf55ef915fedd82b79d963@sha256:aa1e213a2993d0b9c3bf65e511a90b43d54ddfd13d2552f583951ad3c69dc82b # use pre-built to bootstrap 
          name: app-inference
